import type { Metadata } from "next";
import {IBM_Plex_Sans_Arabic,IBM_Plex_Sans } from "next/font/google";
import "./globals.css"
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import Navbar from "@/components/header/navbar";
import Footer from "@/components/footer";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  preload: true,
});

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  preload: true,
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = await getMessages();

  const font = locale === "ar" ? ibmPlexSansArabic : ibmPlexSans;
  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning={true}
        dir={locale === "ar" ? "rtl" : "ltr"}
        className={`${font.className} antialiased bg-white`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar/>
          {children}
          <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
